In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from dotenv import load_dotenv
import os

import warnings
warnings.filterwarnings("ignore")

* Read in Datasets

In [104]:
df1 = pd.read_excel("C:/Users/amare/OneDrive/Desktop/Pycharm practice/datasets/1st Batch.xlsx", sheet_name="Monthly")
df2 = pd.read_excel("C:/Users/amare/OneDrive/Desktop/Pycharm practice/datasets/2nd Batch.xlsx", sheet_name="Monthly")
df3 = pd.read_excel("C:/Users/amare/OneDrive/Desktop/Pycharm practice/datasets/3rd Batch.xlsx", sheet_name="Monthly")

In [105]:
def preprocess(df):
    df = df[4:]
    df = df.drop(range(5, 8))
    df.columns = df.iloc[0]
    df = df.iloc[1:]
    df = df.rename(columns={'title': 'Date'})
    df = df.set_index("Date")
    df.index = pd.to_datetime(df.index)

    return df

In [106]:
df1 = preprocess(df1)
df2 = preprocess(df2)
df3 = preprocess(df3)

In [107]:
def impute_missing(df):
        df = df.fillna(0)
        df = df.round(0).astype('Int64')
        return df

In [108]:
df1 = impute_missing(df1)
df2 = impute_missing(df2)
df3 = impute_missing(df3)

Impute missing values

In [109]:
df3.head()

4,P9: Limpopo — LIC10S00: Modimolle Cluster — T: 25 Serious and Other crimes,P9: Limpopo — LIC10S00: Modimolle Cluster — S: 20 Serious crimes,P9: Limpopo — LIC10S00: Modimolle Cluster — SR: 17 Community reported Serious crimes,P9: Limpopo — LIC10S00: Modimolle Cluster — SRC: Contact crimes (Crimes against the person),P9: Limpopo — LIC10S00: Modimolle Cluster — SRCM: Murder,P9: Limpopo — LIC10S00: Modimolle Cluster — SRCS: Sexual Offences (also see SDS),P9: Limpopo — LIC10S00: Modimolle Cluster — SRCSQ: Attempted sexual offences,P9: Limpopo — LIC10S00: Modimolle Cluster — SRCSC: Contact sexual offences,P9: Limpopo — LIC10S00: Modimolle Cluster — SRCSB: Abduction,P9: Limpopo — LIC10S00: Modimolle Cluster — SRCSR: Rape,...,P9: Limpopo — LIC13S00: Tzaneen Cluster — SDF: Illegal possession of firearms and ammunition,P9: Limpopo — LIC13S00: Tzaneen Cluster — SDN: Drug-related crime,P9: Limpopo — LIC13S00: Tzaneen Cluster — SDD: Driving under the influence of alcohol or drugs,P9: Limpopo — LIC13S00: Tzaneen Cluster — SDS: Sexual Offences detected as a result of police action,P9: Limpopo — LIC13S00: Tzaneen Cluster — O: Other crime categories,P9: Limpopo — LIC13S00: Tzaneen Cluster — OH: Culpable homicide,P9: Limpopo — LIC13S00: Tzaneen Cluster — OV: Public violence,P9: Limpopo — LIC13S00: Tzaneen Cluster — OC: Crimen injuria,P9: Limpopo — LIC13S00: Tzaneen Cluster — ON: Neglect and ill-treatment of children,P9: Limpopo — LIC13S00: Tzaneen Cluster — OK: Kidnapping
Date,,,,,,,,,,,,,,,,,,,,,
2001-01-31,453,421,416,150,0,14,0,0,0,0,...,3,23,13,0,91,8,0,79,1,3
2001-02-28,460,416,411,178,1,9,0,0,0,0,...,2,12,7,0,79,5,0,66,1,6
2001-03-31,537,500,495,219,3,12,0,0,0,0,...,4,1,4,0,92,12,0,71,3,5
2001-04-30,479,441,431,169,3,8,0,0,0,0,...,10,10,3,0,100,8,0,85,5,2
2001-05-31,464,445,436,135,1,6,0,0,0,0,...,7,16,1,0,56,5,0,46,0,5

In [110]:
data = df1.merge(df2, left_index=True, right_index=True, how='outer').merge(df3, left_index=True, right_index=True, how='outer')

In [111]:
data_transposed = data.T.reset_index().rename(columns={4: 'Region'})
data_transposed.head()

Date,Region,2001-01-31 00:00:00,2001-02-28 00:00:00,2001-03-31 00:00:00,2001-04-30 00:00:00,2001-05-31 00:00:00,2001-06-30 00:00:00,2001-07-31 00:00:00,2001-08-31 00:00:00,2001-09-30 00:00:00,...,2024-12-31 00:00:00,2025-01-31 00:00:00,2025-02-28 00:00:00,2025-03-31 00:00:00,2025-04-30 00:00:00,2025-05-31 00:00:00,2025-06-30 00:00:00,2025-07-31 00:00:00,2025-08-31 00:00:00,2025-09-30 00:00:00
0,P9: Limpopo — LIC01S00: Bela Bela Cluster — T:...,567,472,593,540,519,418,543,560,558,...,529,429,436,437,374,455,418,431,523,447
1,P9: Limpopo — LIC01S00: Bela Bela Cluster — S:...,532,443,555,515,486,387,527,529,528,...,511,415,425,425,359,442,400,416,507,432
2,P9: Limpopo — LIC01S00: Bela Bela Cluster — SR...,514,424,540,501,472,373,462,519,510,...,398,329,343,338,293,377,297,294,354,342
3,P9: Limpopo — LIC01S00: Bela Bela Cluster — SR...,209,162,227,204,177,140,163,204,215,...,171,75,117,111,101,97,90,85,106,131
4,P9: Limpopo — LIC01S00: Bela Bela Cluster — SR...,4,2,2,2,5,6,3,8,5,...,4,2,1,2,3,2,3,0,2,1

In [112]:
id_vars = data_transposed.columns[0]
date_cols= data_transposed.columns[1:]

In [113]:
data_long = pd.melt(data_transposed, id_vars=id_vars, value_vars=date_cols, var_name='Date', value_name='Value')
data_long.head()

,Region,Date,Value
0,P9: Limpopo — LIC01S00: Bela Bela Cluster — T:...,2001-01-31 00:00:00,567
1,P9: Limpopo — LIC01S00: Bela Bela Cluster — S:...,2001-01-31 00:00:00,532
2,P9: Limpopo — LIC01S00: Bela Bela Cluster — SR...,2001-01-31 00:00:00,514
3,P9: Limpopo — LIC01S00: Bela Bela Cluster — SR...,2001-01-31 00:00:00,209
4,P9: Limpopo — LIC01S00: Bela Bela Cluster — SR...,2001-01-31 00:00:00,4

In [115]:
data_long[["Province", "Cluster", "Type of Crime"]] = data_long["Region"].str.split("—", expand= True)
data_long["Province"] = data_long["Province"].str.split(":", expand = True).drop(columns= 0)
data_long["Cluster"] = data_long["Cluster"].str.split(":", expand = True).drop(columns= 0)
data_long.head()

,Region,Date,Value,Province,Cluster,Type of Crime
0,P9: Limpopo — LIC01S00: Bela Bela Cluster — T:...,2001-01-31 00:00:00,567,Limpopo,Bela Bela Cluster,T: 25 Serious and Other crimes
1,P9: Limpopo — LIC01S00: Bela Bela Cluster — S:...,2001-01-31 00:00:00,532,Limpopo,Bela Bela Cluster,S: 20 Serious crimes
2,P9: Limpopo — LIC01S00: Bela Bela Cluster — SR...,2001-01-31 00:00:00,514,Limpopo,Bela Bela Cluster,SR: 17 Community reported Serious crimes
3,P9: Limpopo — LIC01S00: Bela Bela Cluster — SR...,2001-01-31 00:00:00,209,Limpopo,Bela Bela Cluster,SRC: Contact crimes (Crimes against the person)
4,P9: Limpopo — LIC01S00: Bela Bela Cluster — SR...,2001-01-31 00:00:00,4,Limpopo,Bela Bela Cluster,SRCM: Murder

In [116]:
data_long["Type of Crime"].unique()

array([' T: 25 Serious and Other crimes', ' S: 20 Serious crimes',
       ' SR: 17 Community reported Serious crimes',
       ' SRC: Contact crimes (Crimes against the person)',
       ' SRCM: Murder', ' SRCS: Sexual Offences (also see SDS)',
       ' SRCSQ: Attempted sexual offences',
       ' SRCSC: Contact sexual offences', ' SRCSB: Abduction',
       ' SRCSR: Rape', ' SRCSA: Sexual Assault', ' SRCSD: Old Abduction',
       ' SRCSI: Old Indecent Assault',
       ' SRCSS: Old Rape and Attempted Rape', ' SRCL: Attempted murder',
       ' SRCH: Assault with the intent to inflict bodily harm',
       ' SRCA: Common assault', ' SRCR: Common robbery',
       ' SRCX: Robbery with aggravating circumstances',
       ' SRCXS: Old Subcategories of Aggravated Robbery',
       ' SRCXR: Robbery: Bank, Street and Cash in transit',
       ' SRCXB: Bank Robbery', ' SRCXC: Robbery of cash in transit',
       ' SRCXO: Street public robbery', ' SRCX3: TRIO Crimes',
       ' SRCX3B: Robbery at non-residential premises',
       ' SRCX3R: Robbery at residential premises', ' SRCX3C: Carjacking',
       ' SRCXT: Truck hijacking', ' SRR: Contact-related crimes',
       ' SRRA: Arson', ' SRRP: Malicious damage to property',
       ' SRP: Property-related crimes',
       ' SRPR: Burglary at residential premises',
       ' SRPB: Burglary at non-residential premises',
       ' SRPV: Theft of motor vehicle and motorcycle',
       ' SRPF: Theft out of or from motor vehicle', ' SRPS: Stock theft',
       ' SRO: Other serious crimes',
       ' SROO: All theft not mentioned elsewhere',
       ' SROC: Commercial crime', ' SROS: Shoplifting',
       ' SD: Crime detected as a result of police action (CDPA)',
       ' SDF: Illegal possession of firearms and ammunition',
       ' SDN: Drug-related crime',
       ' SDD: Driving under the influence of alcohol or drugs',
       ' SDS: Sexual Offences detected as a result of police action',
       ' O: Other crime categories', ' OH: Culpable homicide',
       ' OV: Public violence', ' OC: Crimen injuria',
       ' ON: Neglect and ill-treatment of children', ' OK: Kidnapping'],
      dtype=object)

In [117]:
data_long["Type of Crime"] = data_long["Type of Crime"].replace(' SRCXR: Robbery: Bank, Street and Cash in transit', 'SRCXR: Bank Robbery (Street and Cash in transit)')

In [118]:
data_long["Type of Crime"] = data_long["Type of Crime"].str.split(":", expand = True).drop(columns= 0)

In [119]:
data_long["Type of Crime"].unique()

array([' 25 Serious and Other crimes', ' 20 Serious crimes',
       ' 17 Community reported Serious crimes',
       ' Contact crimes (Crimes against the person)', ' Murder',
       ' Sexual Offences (also see SDS)', ' Attempted sexual offences',
       ' Contact sexual offences', ' Abduction', ' Rape',
       ' Sexual Assault', ' Old Abduction', ' Old Indecent Assault',
       ' Old Rape and Attempted Rape', ' Attempted murder',
       ' Assault with the intent to inflict bodily harm',
       ' Common assault', ' Common robbery',
       ' Robbery with aggravating circumstances',
       ' Old Subcategories of Aggravated Robbery',
       ' Bank Robbery (Street and Cash in transit)', ' Bank Robbery',
       ' Robbery of cash in transit', ' Street public robbery',
       ' TRIO Crimes', ' Robbery at non-residential premises',
       ' Robbery at residential premises', ' Carjacking',
       ' Truck hijacking', ' Contact-related crimes', ' Arson',
       ' Malicious damage to property', ' Property-related crimes',
       ' Burglary at residential premises',
       ' Burglary at non-residential premises',
       ' Theft of motor vehicle and motorcycle',
       ' Theft out of or from motor vehicle', ' Stock theft',
       ' Other serious crimes', ' All theft not mentioned elsewhere',
       ' Commercial crime', ' Shoplifting',
       ' Crime detected as a result of police action (CDPA)',
       ' Illegal possession of firearms and ammunition',
       ' Drug-related crime',
       ' Driving under the influence of alcohol or drugs',
       ' Sexual Offences detected as a result of police action',
       ' Other crime categories', ' Culpable homicide',
       ' Public violence', ' Crimen injuria',
       ' Neglect and ill-treatment of children', ' Kidnapping'],
      dtype=object)

In [127]:
data_long["Type of Crime"] = data_long["Type of Crime"].str.replace(r'\d+\s*','', regex=True)

In [121]:
data_long.drop(columns = "Region", inplace = True)

In [122]:
data_long["Date"] = pd.to_datetime(data_long["Date"])

In [126]:
data_long["Year"] = data_long["Date"].dt.year
data_long["Month"] = data_long["Date"].dt.month_name()
data_long["Day"] = data_long["Date"].dt.day_name()
data_long = data_long[["Date", "Year", "Month", "Day", "Province", "Cluster", "Type of Crime", "Value"]]
data_long

,Date,Year,Month,Day,Province,Cluster,Type of Crime,Value
0,2001-01-31,2001,January,Wednesday,Limpopo,Bela Bela Cluster,Serious and Other crimes,567
1,2001-01-31,2001,January,Wednesday,Limpopo,Bela Bela Cluster,Serious crimes,532
2,2001-01-31,2001,January,Wednesday,Limpopo,Bela Bela Cluster,Community reported Serious crimes,514
3,2001-01-31,2001,January,Wednesday,Limpopo,Bela Bela Cluster,Contact crimes (Crimes against the person),209
4,2001-01-31,2001,January,Wednesday,Limpopo,Bela Bela Cluster,Murder,4
...,...,...,...,...,...,...,...,...
188887,2025-09-30,2025,September,Tuesday,Limpopo,Tzaneen Cluster,Culpable homicide,8
188888,2025-09-30,2025,September,Tuesday,Limpopo,Tzaneen Cluster,Public violence,1
188889,2025-09-30,2025,September,Tuesday,Limpopo,Tzaneen Cluster,Crimen injuria,13
188890,2025-09-30,2025,September,Tuesday,Limpopo,Tzaneen Cluster,Neglect and ill-treatment of children,3
188891,2025-09-30,2025,September,Tuesday,Limpopo,Tzaneen Cluster,Kidnapping,6

In [131]:
for col in data_long.select_dtypes(include = "object").columns:
    data_long[col] = data_long[col].str.strip()

Concat/ Join 1st, 2nd and 3rd batch on index. make date the index